### PR TITLE
updated to use full path

### PR DESCRIPTION
**Pull request by stabback**
`context.route.path` does not include query params.  Update to fullPath to redirect with query params.

### CODE REVIEW

**Comment by jerser** [comment]
Test?

**Comment by stabback** [comment]
@jerser commit message updated.  The existing redirect test has been updated.

**Comment by jerser** [comment]
That doesn't test the actual bug explicitly though imho. I think there should be a test case that has a query string and that verifies it is not omitted.

**Comment by stabback** [comment]
@samtgarson Pinging on this

**Pull request merged**
